name: app_architecture_new
description: "A new Flutter project. For practice new flutter architecture that introduced"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  path: ^1.9.0
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.3.4
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  flutter_svg: ^2.0.16
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  intl: any
  logging: ^1.3.0
  provider: ^6.1.2
  share_plus: ^10.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  mocktail_image_network: ^1.2.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/activities.json
    - assets/destinations.json
    # - assets/logo.svg
    - assets/user.jpg
  fonts:
    - family: IRANSans
      fonts:
        - asset: assets/fonts/IRANSans_Black.ttf
          weight: 900
        - asset: assets/fonts/IRANSans_Bold.ttf
          weight: 700
        - asset: assets/fonts/IRANSans_Medium.ttf
          weight: 500
        - asset: assets/fonts/IRANSans.ttf
          weight: 400
        - asset: assets/fonts/IRANSans_Light.ttf
          weight: 300
        - asset: assets/fonts/IRANSans_UltraLight.ttf
          weight: 200
